[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "2VsDgBxxmv6cyKAJjjmKHggt777rN4ELvQ2W6yCzzpqp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ef/my-solana-wallet/my-keypair.json "

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
